### ISSUE TITLE
怎么适配其他的m3u8直播网站？比如小鹅通，微赞这类

### ISSUE THREAD

**Issue by lweo** [Harlan-H/M3u8Downloader_H#10]
能做到对所有的未加密的m3u8直播通用吗？

测试地址：
https://liveplay-dx.xiaoeknow.com/live/5060_SAXCJiJQKpEQe8jT.m3u8?time=1670739297272&uuid=u_lp_1641695467_61da48ebac290_aBMSlc

https://pull-hw1.videocc.net/recordf/afec5c2a3516696117588067c9b.flv?txSecret=7a6b7efc94789b31f9fbfb8d054baadb&txTime=63957232&pid=1670738577043X1675812&param1=MTY3MDczODU3NjcxMA&client=PCH5Live-1.38.8&playerId=1670738577040X1200298&pd=0&cts=0&ran=2023368

我这里显示restapi初始化失败，是正常的吗？

**Comment by Harlan-H** [comment]
适配是通过软件得插件开发实现得  
通用咋可能 每个网站得布局 数据都不一样 不可能通用得  只能尽可能得多得适配上
那如果你也是开发者 同时也会c#  你可以参考一下 我已经写好得插件 你就可以做适配了 
至于restapi初始化失败得问题 如果你不知道restapi干啥得 那这个功能对你就没用  他即使失败也不影响程序正常下载

**Comment by Harlan-H** [comment]
我说得适配是 不需要m3u8地址得那种适配  
如果只是m3u8地址 那无所谓 这个本来就都是通用得 
如果出现报错 你只要看一下 他具体报错得是啥 然后做针对性得处理就可以了

**Comment by lweo** [comment]
> 我说得适配是 不需要m3u8地址得那种适配 如果只是m3u8地址 那无所谓 这个本来就都是通用得 如果出现报错 你只要看一下 他具体报错得是啥 然后做针对性得处理就可以了

感谢你的迅速回复！
对于那种通过flv直播的比较简单的网站，能做到通用吗？
没加密，不需要cookie，复制直链就能下载，比如微博直播，蔻享（https://www.koushare.com/lives/room/***）
智社（https://www.smartsowo.com/live/detail/269）

**Comment by lweo** [comment]
> 适配是通过软件得插件开发实现得 通用咋可能 每个网站得布局 数据都不一样 不可能通用得 只能尽可能得多得适配上 那如果你也是开发者 同时也会c# 你可以参考一下 我已经写好得插件 你就可以做适配了 至于restapi初始化失败得问题 如果你不知道restapi干啥得 那这个功能对你就没用 他即使失败也不影响程序正常下载

大学时是学过一点C#，不过现在都快忘了。。

有插件可以自动获取到m3u8链接，软件是否也可以做到？获取到然后自动下载？

**Comment by Harlan-H** [comment]
软件是m3u8下载器 所以只针对m3u8 其他格式得 你用啥都可以下载 
插件 我说得是我软件得插件 不是别得插件
我已经写好几个插件了  那几个站 都不需要获取m3u8 直接视频地址就可以完成下载 
你可以去看一下 咋操作得  你要想适配 你也可以自己写插件
对于开发者来说 这些东西 应该不是太难

**Comment by Harlan-H** [comment]
你不是开发者得话 那这个就没办法了 
最起码 都得要会一点语言  哪怕是python都成 
用python可以通过rest api来实现下载等 通用解决方案
那会c#就更好 直接实现接口  就可以做到 适配任何站点
而且你发得那两个站 我也有进去看过 他都是flv得格式  适配也没用 
flv得格式 虽然找一个 通用得下载工具都可以下载  那个没必要适配
如果你想用c#开发插件得话 你可以卡一下wiki或者项目主页中有个在线帮助文档 或者 我写好得插件项目 都行

**Comment by lweo** [comment]
> 你不是开发者得话 那这个就没办法了 最起码 都得要会一点语言 哪怕是python都成 用python可以通过rest api来实现下载等 通用解决方案 那会c#就更好 直接实现接口 就可以做到 适配任何站点 而且你发得那两个站 我也有进去看过 他都是flv得格式 适配也没用 flv得格式 虽然找一个 通用得下载工具都可以下载 那个没必要适配 如果你想用c#开发插件得话 你可以卡一下wiki或者项目主页中有个在线帮助文档 或者 我写好得插件项目 都行

小鹅通和微赞是m3u8直播，这上面的学术直播很多，可以考虑适配下 :)
