### ISSUE TITLE
是不是还不支持SAMPLE-AES，skd://这样的key？

### ISSUE THREAD

**Issue by kurtn2005** [Harlan-H/M3u8Downloader_H#11]
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://ChDy656Hr-4xToOFUpIfaK4oEhDlvHJq1JVNUUK3TFDtlI22GpIBeyJ2IjoiMiIsImZpZCI6IjUzZHYwMTUyMSIsInN2aWQiOiJkaWdpdGFsIiwicGwiOiJleUp3YVdRaU9pSTFNMlIyTURFMU1qRWlMQ0prWld4cGRtVnllVjkwZVhCbElqb2ljM1FpZlEiLCJjcyI6IjA0M2VjN2RhNWE0NDdkM2Y5NTE5Y2VkZmQ3NzE5OTliIn0",IV=0xe5bc726ad4954d5142b74c50ed948db6,KEYFORMAT="com.apple.streamingkeydelivery"

下载DMM发现它更新了加密方式，不是以前的drm_phone那种方式了，查了一下好像需要通过网络获取key。

**Comment by Harlan-H** [comment]
SAMPLE-AES 肯定不支持得 
还有就是 你这个uri压根不是http地址  
而且从你发出来得这个数据来看 他应该是自己实现了某种加密方式
那这样得话 就需要你自己会分析  来修改m3u8文件  来下载
或者也你可以通过软件得插件方式 直接适配这个内容
那这些 你都没法做得话 你也可以给获取到这个m3u8内容得地址 最好是视频地址留下来  我有时间得话 可以去分析一下

**Comment by kurtn2005** [comment]
> 
这个是Playlist用来获取码率的，最高码率应该是6M的。
https://stc013.dmm.com/digital/st3.0:+jjiLCGO0t2zGxkzZjxeNOVyhb15nPe7ulfBUk18oil1rBhwgo05UbxwjVFd6Ys5W4ySMzWRx408Gcm-l-E9xYkhaKZAzdjq95CQ9NgkYczLmvOrqEMACmtfho1uIL-0o-SOBXItsNb8PY+yO3sTLR8tIElg44ujqkryVjq+KxC9FZAdh3k6NkWK2Ersn7Xp/7U7vM6ccjpT6JaaZOTWl49Nkwzxh/-/playlist.m3u8

6M的播放地址。chunklist_b6000000.m3u8
https://stc013.dmm.com/digital/st3.0:+jjiLCGO0t2zGxkzZjxeNOVyhb15nPe7ulfBUk18oil1rBhwgo05UbxwjVFd6Ys5W4ySMzWRx408Gcm-l-E9xYkhaKZAzdjq95CQ9NgkYczLmvOrqEMACmtfho1uIL-0o-SOBXItsNb8PY+yO3sTLR8tIElg44ujqkryVjq+KxC9FZAdh3k6NkWK2Ersn7Xp/7U7vM6ccjpT6JaaZOTWl49Nkwzxh/-/chunklist_b6000000.m3u8

不知道你能否用这个地址，这份m3u8里面一共有1790个ts切片，下回来都是灰图像，因为不支持这个解密。

skd:// 这个我查了一下貌似是Apple用的FairPlay，具体我不懂了，大神能帮忙看看最好。谢谢。

**Comment by Harlan-H** [comment]
你给我这个地址是没用得 
你必须给我获取这个地址得 那个网站才可以

**Comment by kurtn2005** [comment]
好的，我看看能不能私信你我的账号密码。发自我的 iPhone在 2022年12月12日，22:08，Harlan ***@***.***> 写道：﻿
你给我这个地址是没用得
你必须给我获取这个地址得 那个网站才可以

**Comment by kurtn2005** [comment]
没找到能私信的地方……用tg？

**Comment by Harlan-H** [comment]
你要不直接留个网址  我倒时候 看了之后  再说把

**Comment by kurtn2005** [comment]
www.dmm.co.jp需要账号就发我邮箱我发你。发自我的 iPhone在 2022年12月13日，19:25，Harlan ***@***.***> 写道：﻿
你要不直接留个网址  我倒时候 看了之后  再说把
