### ISSUE TITLE
B站的直播下载不稳定？

### ISSUE THREAD

**Issue by lweo** [Harlan-H/M3u8Downloader_H#12]
有log文件吗？有个直播只下了25分钟，我设置的最长下载是4h…

**Comment by Harlan-H** [comment]
你i发个地址 我看看 
b站的直播 我确实也遇到过  不稳定的情况  但是没法100%复现  所以就不好修复

**Comment by lweo** [comment]
> 你i发个地址 我看看 b站的直播 我确实也遇到过 不稳定的情况 但是没法100%复现 所以就不好修复

任务我都情况了。。
