### ISSUE TITLE
有时出现下载时长和实际时长不一致的情况，什么原因？

### ISSUE THREAD

**Issue by lweo** [Harlan-H/M3u8Downloader_H#14]
(https://apppuhyjuw08416.h5.xiaoeknow.com/v2/course/alive/l_63427b47e4b050af23c1e4ac?type=2&resource_type=4&resource_id=l_63427b47e4b050af23c1e4ac&app_id=apppuhyjuw08416&pro_id=p_634bb6bfe4b0a51fef298078)

这个会议下午下了3个多小时（会议时长是3个多小时），下载结束后打开视频才1个多小时，进度条拖到最后，确实也只有1个多小时…

是我设置问题吗？怎么设置能增强直播下载的稳定性？
![image](https://user-images.githubusercontent.com/2786659/208699909-4509c492-3f2b-4728-9928-1af102c98a6f.png)

**Comment by Harlan-H** [comment]
首先这个软件不是傻瓜式软件 
他不是说给地址  就可以一定下载来  
给地址一定可以下载下来 那个是网站对下载没有任何得检测 
但是你录制这种东西  尤其这个还是小鹅通  如果你不会分析得话  那录制不全也很正常
但是我可以大致跟你说一下 很多网站一般需要登录得 都会检测请求头  绝大部分是检测cookie
而且你这个网站 目前没有直播 那我也不清楚下一次啥时候会开播 你回头看到了 跟我说一下 下次开播时间  
我来论证 我得猜想
