### ISSUE TITLE
新的m3u8解密能加上吗

### ISSUE THREAD

**Issue by 458722** [Harlan-H/M3u8Downloader_H#15]
m3u8 大部分站 现在都是这种加密方式
https://kr46.sogirl.so/stars-758-%ec%95%84%ec%98%a4%ec%a1%b0%eb%9d%bc-%ed%9e%88%ec%b9%b4%eb%a6%ac-hd/
还有
https://kbjav.com/
https://supjav.com/
这些都是一种加密方式。有办法添加上吗？

**Comment by Harlan-H** [comment]
你说的第一个  我没进去 
但是你说的 后面的所有的加密方式  我测试过 没有任何加密
报错也报的是403  不是加密错误 
所以这个是网站的检测 跟加密没有任何关系
但是他们网站确实都加了轻微的反调试 
如果你不懂的话 你可以去看52pojie 我发过的一篇帖子 帖子开头就有说过如何过掉这个反调试
https://www.52pojie.cn/thread-1671722-1-1.html

下面是下载成功的图
![image](https://user-images.githubusercontent.com/39378318/211180604-ef6a602b-807b-48cd-a88a-e5b32e0785fb.png)
