### ISSUE TITLE
请问，可以增加个监控抖音直播并自动开启录制的功能吗？

### ISSUE THREAD

**Issue by codercplus** [Harlan-H/M3u8Downloader_H#16]
具体：类似将作者加入监控列表，每隔X分钟检测一下直播间状态。一旦对方正在直播，则自动开启录制。这样可以保证不错过直播。

目前网上上具有类似功能的软件都失效了。

**Comment by Harlan-H** [comment]
软件是m3u8通用下载器  不针对某一个平台  
能支持直接提交抖音的直播地址 就下载也只是为了方便你不用手动去取m3u8地址 仅此而已
所以你说对直播间监控 这就不现实了
但是软件提供了诸多的对接方案 你可以采用其他的方式跟软件对接 通过其他语言监控取到m3u8地址发给下载器下载

**Comment by Harlan-H** [comment]
软件是m3u8通用下载器  不针对某一个平台  
能支持直接提交抖音的直播地址 就下载也只是为了方便你不用手动去取m3u8地址 仅此而已
所以你说对直播间监控 这就不现实了
但是软件提供了诸多的对接方案 你可以采用其他的方式跟软件对接 通过其他语言监控取到m3u8地址发给下载器下载
