### ISSUE TITLE
下载过程中报错

### ISSUE THREAD

**Issue by JackShuai8** [Harlan-H/M3u8Downloader_H#17]
![image](https://user-images.githubusercontent.com/53900613/233239971-9d5b70b1-3194-4bd6-9a17-13385a88d6d8.png)
你好 我在下载视频的时候，每隔一段时间就会出现下载报错的问题，查看原因显示如上图，请问这大概是什么问题呢

**Comment by Harlan-H** [comment]
这个提示的其实很明确的  就是数据不完整 
那产生不完整的原因有很多的  
有的是服务端的网络延迟啊 
如果你在下载途中没有报错的话 那基本就是网络延迟导致的 
那你只能想办法让网络顺畅才行 
因为数据不完整的话 合并时没有意义的

**Comment by JackShuai8** [comment]
好的好的  感谢(^o^)／
