### ISSUE TITLE
看文件是下载成功的，毕竟有文件大小。但是还差合并的时候出错

### ISSUE THREAD

**Issue by wushendutang** [Harlan-H/M3u8Downloader_H#18]
System.InvalidOperationException: ffmpeg异常退出 退出码 (1).
参数:
-allowed_extensions ALL -i D:\ruanjian\M3u8Downloader_H\download\19ad4b8cfc1d4d23ae703d023d5f4e70\generated.m3u8 -f mp4 -c:a copy -c:v copy -nostdin -y D:\ruanjian\M3u8Downloader_H\download\19ad4b8cfc1d4d23ae703d023d5f4e70.mp4
错误是:
ffmpeg version 4.4.1-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 000001f8334dc500] Opening 'D:\ruanjian\M3u8Downloader_H\download\19ad4b8cfc1d4d23ae703d023d5f4e70\1.tmp' for reading
[hls @ 000001f8334dc500] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, hls, from 'D:\ruanjian\M3u8Downloader_H\download\19ad4b8cfc1d4d23ae703d023d5f4e70\generated.m3u8':
  Duration: 00:01:00.11, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: png, none(pc), 25 tbr, 25 tbn, 25 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'D:\ruanjian\M3u8Downloader_H\download\19ad4b8cfc1d4d23ae703d023d5f4e70.mp4':
Output file #0 does not contain any stream

   at M3u8Downloader_H.Core.VideoConverter.FFmpeg.ExecuteAsync(String arguments, IProgress`1 progress, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloaderSource.ConverterToMp4(String m3u8FilePath, Boolean allowed_extensions, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloaderSource.ConvertWithM3u8File(CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloaderSource.Converter(Boolean isFile, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadVodSource.DownloadAsync(CancellationToken cancellationToken)
   at M3u8Downloader_H.Services.DownloadService.DownloadAsync(IDownloaderSource downloaderSource, DownloadRateSource downloadRate, CancellationToken cancellationToken)
   at M3u8Downloader_H.ViewModels.DownloadViewModel.<OnStart>b__41_0()
下载的东西：nos.netease.co谷谷谷谷m/yanxuan/fa9fa2d7咕咕咕咕8b13ba4ae62c737b89a33cff.m3u8
版本是下载最新的

**Comment by Harlan-H** [comment]
感谢提交问题 近日将更新此问题
