### ISSUE TITLE
直播的key动态加密有办法处理吗？我想中转这个信号源。

### ISSUE THREAD

**Issue by 66508393** [Harlan-H/M3u8Downloader_H#19]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:29031
#EXT-X-TARGETDURATION:4
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn-key.hkdtmb.com/81/1688002981505.key",IV=0x00000000000000000000018904D16E81
#EXTINF:4.000,
1688003008966.ts
#EXTINF:4.000,
1688003013382.ts
#EXTINF:4.000,
1688003017421.ts
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn-key.hkdtmb.com/81/1688003020776.key",IV=0x00000000000000000000018904D207E8
#EXTINF:4.000,
1688003020776.ts
#EXTINF:4.000,
1688003025089.ts
#EXTINF:4.000,
1688003031821.ts
#EXTINF:4.000,
1688003034696.ts
#EXTINF:4.000,
1688003036634.ts
#EXTINF:4.000,
1688003040654.ts
#EXTINF:4.000,
1688003049166.ts
#EXTINF:4.000,
1688003050790.ts
#EXTINF:4.000,
1688003052642.ts
#EXTINF:4.000,
1688003056849.ts
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn-key.hkdtmb.com/81/1688003060849.key",IV=0x00000000000000000000018904D2A471
#EXTINF:4.000,
1688003060849.ts
#EXTINF:4.000,
1688003065419.ts

**Comment by Harlan-H** [comment]
那你只能自己扩展插件了 如果你不会c#开发的话 那我无能为力 
毕竟你这种情况非常特殊

**Comment by Harlan-H** [comment]
只不过 你这个东西 感觉有点意思 你如果愿意提供地址的 我倒是可以考虑适配一下
