### ISSUE TITLE
大大包里有ffmpeg，怎么不设计合并转码

### ISSUE THREAD

**Issue by whxuezhe** [Harlan-H/M3u8Downloader_H#21]
你参考下这段批处理：这是ts转为mp4的，不过这个不完善；会把分集的同源文件合并为一集，你顺着这个思路搞就好。谢谢！
SetLocal EnableDelayedExpansion
echo.>0.txt
for /f "delims=" %%a in ('dir /b/a-d *.ts') do (
 echo %cd%\%%a>>0.txt
)
for /f "delims=" %%i in (0.txt) do (
   set str=%%i
   set "str=!str:E:=file 'E:!"
   set "str=!str:.ts=.ts'!"
   echo !str!>>1.txt
)
move 1.txt 0.txt
ffmpeg.exe -f concat -safe 0 -i 0.txt -c copy out.mp4
pause
rem -safe 0: 防止Operation not permitted
rem dir /s /b *.ts> 0.txt此命令会列举子文件夹ts

**Comment by Harlan-H** [comment]
https://github.com/Harlan-H/M3u8Downloader_H/wiki/%E5%9F%BA%E6%9C%AC%E5%8A%9F%E8%83%BD#4%E5%BF%AB%E9%80%9F%E5%90%88%E5%B9%B6

https://note.youdao.com/ynoteshare/index.html?id=c6ba2fb478ad300b7095c7c951556fc6&type=notebook&_time=1690264470742#/EEA11A288BA54B71842DDC74CA8E15CA
