### ISSUE TITLE
请求添加PP体育解析下载

### ISSUE THREAD

**Issue by yyxiaofeng** [Harlan-H/M3u8Downloader_H#22]
类似http://sports.pptv.com/vod/pg_h5video/31569351/8118189?from=pptv这样的视频，识别出来是一段一段MP4，下载太费劲了，请求大佬增加支持解析下载功能

**Comment by Harlan-H** [comment]
软件只支持m3u8格式得视频下载  你发得这个好像是mp4得 是不支持下载得 
目前没有太多的人反馈有需要这种mp4下载的需求 
所以我也没有做  如果需要得人多得话 可以考虑加入mp4下载相关得功能

**Comment by yyxiaofeng** [comment]
大佬能否帮忙看下如何提取到m3u8链接，感激不尽

**Comment by Harlan-H** [comment]
你可以尝试手机版 
很多类似得网站手机版会采用m3u8格式
比如抖音直播 手机版就是m3u8格式

**Comment by yyxiaofeng** [comment]
好的吧
