### ISSUE TITLE
音频下载

### ISSUE THREAD

**Issue by libixi123** [Harlan-H/M3u8Downloader_H#24]
大佬，能够新增批量下载音频功能，提取在线视频中的音频，转换选项增加MP3

**Comment by Harlan-H** [comment]
目前软件连mp4下载都不支持 那就更没有办法直接说 下载mp3  
因为不管下载mp3或者mp4都是一样的玩法 
他跟下载m3u8 有很大的区别
而且目前来说 没有太多的人反馈说需要下载mp4的功能 
所以目前还没有增加的可能 等后期吧 
到时候如果真的增加了mp4下载功能的话 可以考虑你这个需求
