### ISSUE TITLE
请求添加命令操作功能，如在windows上使用bat等命令操作

### ISSUE THREAD

**Issue by lanpeng1612** [Harlan-H/M3u8Downloader_H#25]
请求添加命令操作功能，如在windows上使用bat等命令操作

在下载多个视频时操作相对繁琐重复，如果可通过bat等命令来调用，可简化重复操作，如填写链接和名字

**Comment by Harlan-H** [comment]
bat的方式 这个操作的话 一般是你们自己写的   因为bat一般来说是发起源  他就跟使用python之类的编程语言发起调用时一个道理
但是我软件是接收源 不限制你发起源使用啥语言
至于其他的下载方式 我在帮助文档里写了很多  
通过txt文档批量下载的 通过python下载的 应该来说绝对满足目前几乎所有下载的需求
帮助文档两个地址：https://github.com/Harlan-H/M3u8Downloader_H/wiki/%E5%9F%BA%E6%9C%AC%E5%8A%9F%E8%83%BD
http://note.youdao.com/noteshare?id=c6ba2fb478ad300b7095c7c951556fc6

**Comment by lanpeng1612** [comment]
> bat的方式 这个操作的话 一般是你们自己写的 因为bat一般来说是发起源 他就跟使用python之类的编程语言发起调用时一个道理 但是我软件是接收源 不限制你发起源使用啥语言 至于其他的下载方式 我在帮助文档里写了很多 通过txt文档批量下载的 通过python下载的 应该来说绝对满足目前几乎所有下载的需求 帮助文档两个地址：https://github.com/Harlan-H/M3u8Downloader_H/wiki/%E5%9F%BA%E6%9C%AC%E5%8A%9F%E8%83%BD http://note.youdao.com/noteshare?id=c6ba2fb478ad300b7095c7c951556fc6

看了文档感觉这是我最关心的问题了
1、txt文档的m3u8的文件格式是否能修改为其他格式如：https://tiankongzy.cc/网站格式
第09集$https://v9.dious.cc/20230621/5V0UFXmS/index.m3u8
2、文档中提到”批量操作时，软件上的视频名称 没有任何作用“，考虑到要选择的是电视剧类型的还是不太方便

我之所以提到用bat来操作是，通过bat来接管这款软件的
1、地址信息输入，如：遇到这些格式，数量比较多修改相对麻烦
第09集$https://v9.dious.cc/20230621/5V0UFXmS/index.m3u8
第09集 https://v9.dious.cc/20230621/5V0UFXmS/index.m3u8
2、视频名字
在遇到电视剧类型的文件需要名字加集数来区分

Http Rest API 这个项目没看懂视乎很有趣，是用python下载资源的教程吗
https://github.com/Harlan-H/M3u8Downloader_H/wiki/Http-Rest-API
最近正在学习如何爬取555的视频资源，但还未能获取指向到m3u8地址的真正链接，似乎少了url传递参数值

如果可以能否请你帮我写个获取555视频资源的教程

非常感谢你开发的这款工具并开源让我们有机会使用，下载是真的很快

**Comment by Harlan-H** [comment]
兄弟  我这软件到底多少人在用  我不知道 但是很多在用的人早以习惯我软件的这种方式
我突然改变批量添加的方式 那那些用户咋办 他们的习惯不是也得改嘛  
至于批量下载方式 我文档里应该写的很清楚 你自己自行修改成我软件对应的格式
至于名字 我是说 当你使用批量下载方式  软件上那个视频名称没有效果  不代表你在批量下载里的视频名称没有效果  
为了防止歧义 我还还放的截图诶  你看截图里 那个批量下载 他也是有名字的
至于你后面说的那个啥555视频资源 是啥网站我也不清楚

**Comment by lanpeng1612** [comment]
> 兄弟 我这软件到底多少人在用 我不知道 但是很多在用的人早以习惯我软件的这种方式 我突然改变批量添加的方式 那那些用户咋办 他们的习惯不是也得改嘛 至于批量下载方式 我文档里应该写的很清楚 你自己自行修改成我软件对应的格式 至于名字 我是说 当你使用批量下载方式 软件上那个视频名称没有效果 不代表你在批量下载里的视频名称没有效果 为了防止歧义 我还还放的截图诶 你看截图里 那个批量下载 他也是有名字的 至于你后面说的那个啥555视频资源 是啥网站我也不清楚

哈哈哈，我不是想需要些什么，我可能没有表达清楚，还请见谅。
我前面的意思是想如果给软件添加命令操作的方式，这样软件可使用界面操作同时又能使用命令操作如cmd命令那般操作。
可惜目前我还看不懂这些，不然我也能尽些绵薄之力

我前面提到的555影视是https://5dy15.cc/这个网站，应该和插件中的555影视站一样把，可不知到为什么我使用插件无法解析下载资源

**Comment by Harlan-H** [comment]
主要程序本身他就是带界面得  就是为了避免那些复杂得命令方式操作   
因为有界面得话 对于用户来说 他得学习成本是非常低得  
但是又考虑到一些高端玩家可能会一些高级得操作 所以才提供了完整得rest api 玩法
因为命令行操作得话 他必须要再程序启动之前 传入参数来操作 实际比双机打开操作还要麻烦很多
而且目前我也不太清楚 你所要得那个效果具体是啥样得 所以目前只能这样

还有就是那个插件没更新啊 网站更新了 那个插件只支持旧版得  等我有时间更新一下

**Comment by Harlan-H** [comment]
你说得是不是那种啊 
cs游戏里 按某个键就会出来一个可以出来一个控制台 是那个嘛
如果说得是那个得话 我到感觉真得给我提供了一个新思路 还真可以考虑加进去

**Comment by lanpeng1612** [comment]
你提到的这个视乎也可以
其实我想说的是这个效果如在cmd窗口输入：
.\M3u8Downloader_H.exe [参数]
.\M3u8Downloader_H.exe --save-dir
Options:
  --tmp-dir <tmp-dir>                      设置临时文件存储目录
  --save-dir <save-dir>                    设置输出目录
  --save-name <save-name>                  设置保存文件名
  --base-url <base-url>                    设置BaseURL
就像上面的一样只需要这几个功能被调用即可其他的参数过于复杂，而只需要这几个常用的即可

如果我想下载的视频资源 https://5dy15.cc/
用python要如何取获取视频的m3u8链接所在的数据，并可以进行循环爬取操作呢

**Comment by lanpeng1612** [comment]
我的想法是用python来获取m3u8地址保存起来，再用命令直接调用这个软件来下载资源

**Comment by Harlan-H** [comment]
那还是这种命令行 这种没啥意义 做界面得主要目的 就是为了抛弃这个用法
而且你用python得话 你直接把地址啥得发送给软件 不就下载了 何必这么麻烦还保存起来
在rest api中有代码实例   可以参考一下

**Comment by lanpeng1612** [comment]
好的，能教我一下如何获取https://5dy15.cc/，这个网站的视频资源不，我一直没能找到m3u8链接所在的位置

**Comment by Harlan-H** [comment]
这个网站不适合初学者 
如果你不是这个行业得  也不会js python之类得编程语言 那你最好放弃这个网站 换一个简单得搞

**Comment by lanpeng1612** [comment]
目前在学python，这个网站的m3u8的链接可通过抓包或浏览器插件提取出来，我想python应该也能做到
headers = {
    # User-Agent 用户代理 表示浏览器基本身份信息
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36'
}

url = requests.get("https://movie.douban.com/top250?start=0&filter=",headers=headers)

element = etree.HTML(url.text)

element_s = element.xpath('//*[@id="content"]/div/div[1]/ol/li[1]/div/div[2]/div[1]/a/span/text()')

print(element_s)
这样只能提取到html内容，通过抓包可看到这条信息，我主要是不清楚，当我们点击视频播放，浏览器发送了什么才得到这条地址信息的，希望你能思路
GET https://vip.ffzy-play3.com/20221228/5608_482c0fb7/2000k/hls/mixed.m3u8
200 OK (application/vnd.apple.mpegurl)

**Comment by Harlan-H** [comment]
兄弟 我已经跟你说了 这网站不适合初学者 
你一定偏要硬搞得话 我只能说 祝你好运
这个网站跟其他网站不一样  别得网站很多都是直接把地址嵌入到网页内得 所以你可以直接通过那段代码就拿到
但是这个网站 他得地址是加密得 然后加密得那段js是混淆得  你想拿到那段代码 需要先还原那整个js 或者硬调试  
但是调试 他有反调试    所以这个不是思路得问题 
如果你能找到那个参数得一些来源啥得 你一定会找到那个混淆过得js  一定会遇到反调试 
这些你都没有说 说明你是纯新手 
还是那句话 建议搞别得网站 这个网站不适合你

**Comment by lanpeng1612** [comment]
好吧，我原以为浏览器插件和idm可以直接获取到m3u8地址，就应该也很简单，感觉原理差不多，看来是我想的太美好了

对了我提个建议，感觉可在程序里添加个在线播放，网络流畅就直接看了，好像类似能在线播放m3u8地址的工具不多，或是调用播放器来播放，要批量播放的，看电视剧用的上

刚刚python调用这款工具使用感觉别扭了些，需要先打开程序才能使用，打开程序的弹窗可以直接最小化，我感觉如果都用python调用了就没必要在弹出窗口了

在使用批量下载时可用一个名字加上数字排序，先定义一个名字，再感觉链接顺序来排序，可做的视频名加上每一个的集数在播放视频时还是蛮方便的

非常感谢你提供的帮助
