### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by antidote02** [Harlan-H/M3u8Downloader_H#29]
3.14.3
![屏幕截图 2024-05-19 032424](https://github.com/Harlan-H/M3u8Downloader_H/assets/62492194/958705fc-4709-45d4-9ad5-a78bfbe8ef54)

3.14.2正常
![image](https://github.com/Harlan-H/M3u8Downloader_H/assets/62492194/30624e2f-24df-4ae8-84e6-2ae9e3da6119)
但非管理员身份运行时关闭弹窗未响应
![image](https://github.com/Harlan-H/M3u8Downloader_H/assets/62492194/74730a91-4e1b-4951-9156-358baadff9ef)

**Comment by q3866845** [comment]
M3u8Downloader_H-SingleFile 3.14.3同样的弹窗
3.14.2正常

**Comment by HuLZ688** [comment]
我也一样，3.14.3不行，3.14.2就可以了

**Comment by lmrpx** [comment]
俺也一样

**Comment by flage256** [comment]
同样的问题

**Comment by WHUrology** [comment]
Edition	Windows 10 Home 64bit
Version	22H2
Installed on	‎6/‎6/‎2020
OS build	19045.4412
Experience	Windows Feature Experience Pack 1000.19056.1000.0

一样的问题，3.14.3无法运行。

**Comment by Harlan-H** [comment]
是怎么个事  管理权限没有问题？  非管理员权限 不行？

**Comment by Harlan-H** [comment]
你们尝试把插件目录给删除 因为那个插件相关内容有所更改 可能会导致这个错误的出现 
而且目前新版插件还没更新 这是一个折中方案  
如果插件目录删除之后 没有这个错误的话 可以在给发一下消息

**Comment by Harlan-H** [comment]
下载最新版

**Comment by HuLZ688** [comment]
win10实测3.14.4已经修复成功

**Comment by antidote02** [comment]
已fixed，支持

**Comment by k476445621** [comment]
为什么3.14.4版本清除缓存的功能失效了！
