### ISSUE TITLE
Rest API只能本机访问

### ISSUE THREAD

**Issue by 1144822034** [Harlan-H/M3u8Downloader_H#30]
怎么修改为任意其它地址设备都能访问API

**Comment by Harlan-H** [comment]
软件是同时监听内网和外网端口的 不存在你说的只能本机访问的问题
只要是局域网内的都可以访问 
如果软件是跑在公网设备上的 那需要你自己配置公网的端口映射 同时直接向公网ip发请求 即可操作

**Comment by Harlan-H** [comment]
这个功能出现的时候 就已经做过测试 没有任何问题
再给你发这个消息之前 我又进行了测试  任然是可以正常的

**Comment by 1144822034** [comment]
![image](https://github.com/Harlan-H/M3u8Downloader_H/assets/60906628/537b78b0-577a-4f4f-9c6c-2c94391ad194)

![baa11e3c5b4248d6cdcdf1994351371](https://github.com/Harlan-H/M3u8Downloader_H/assets/60906628/29562135-39ae-4d85-8ad1-114251ec0290)

如图，我用其它手机，同局域网，访问192.168.0.105:65432会无响应

**Comment by Harlan-H** [comment]
这个是给开发者用的 不是让你用浏览器访问的  
具体操作方法 ：https://github.com/Harlan-H/M3u8Downloader_H/wiki/Http-Rest-API

**Comment by Harlan-H** [comment]
我都忘了 你这样访问也是没有问题的 
![image](https://github.com/Harlan-H/M3u8Downloader_H/assets/39378318/82eb979c-f273-4cd7-9039-98b0c0086c8c)
而且我也测试了 是没有任何问题
只有你为啥不行 你需要自行检查你的网络问题 或者相关的情况

**Comment by 1144822034** [comment]
好的，感谢解答

**Comment by Harlan-H** [comment]
但是我可以给你提示一下 一般这类情况 最大的问题 都是出再防火墙上  
一般比较粗暴的方案是 你在哪台机器上运行的这个软件 你就给那个机器的防火墙关了 然后重启电脑 大多就都可以连通了
至于其他的解决方案 可以需要你自己试了
