### ISSUE TITLE
下载下来的视频，合并出来后使用ffmpeg或者ffprob或者Opencv解析的时长不正确，

### ISSUE THREAD

**Issue by aloxc** [Harlan-H/M3u8Downloader_H#35]
如题，比如下载下面这个，https://cdn14.yzzy-tv1.com/20230704/28373_a2a40989/index.m3u8
使用迅雷或者M3u8Downloader_H下载下来的都是703个ts片段，并且大小都一样，

是否能保留.m3u8文件，合并的时候使用.m3u8来合并ts，这样就没问题的了

**Comment by Harlan-H** [comment]
第一个问题那个地址我下载是正常的 并没有你说的所有的ts文件大小都一样的情况 软件正常下载 正常转码 正常播放

第二个你说的保留m3u8文件 其实没有太大必要  软件提供了多种合并方案 不一定就必须要用m3u8格式来合并 所以保留m3u8文件的意义就不是很大了

**Comment by aloxc** [comment]
你好，我的意思是说，可以下载，下载完毕合并（转码格式使用默认，不使用ffmpeg，使用ffmpeg是正常的）后，你使用ffprobe命令查看下合并后的视频时长，再使用别的播放器打开，看看视频时长，两者不一致，我使用ffprobe查看视频时长只有几秒。

这个地址如果使用迅雷下载，下载完毕后使用ffmpeg -i index.m3u8 -vcodec copy -acodec copy out.mp4 合并结果使用ffprobe查看视频时长就是正确的，

**Comment by Harlan-H** [comment]
这个应该是视频网站 本身的视频导致的问题 
默认只是合并而已  是不会处理视频相关的任何内容 
你用ffmpeg转码的时候 他是会去处理的 可能会清除掉一些无用数据啊 或者不识别的数据等
我也用这个啥ffprobe测试了一下 我的显示只有17秒 
播放器估计是兼容吧 他可能处理的比较完善
软件本身 不会对视频做任何的修改  因为一旦修改 视频就播放不了了

**Comment by aloxc** [comment]
嗯，好的，

给您提点建议，成功或者失败的时候提示音有点刺耳，可以找点轻柔点的音效。
