### ISSUE TITLE
你好，当迅雷开着的时候，右键复制链接等异常

### ISSUE THREAD

**Issue by aloxc** [Harlan-H/M3u8Downloader_H#36]
如题，当还有任务的时候，不管任务的状态如何，右键复制链接什么的时候会发生异常，请修复。谢谢

**Comment by Harlan-H** [comment]
异常 怎么个异常法  有视频嘛 或者图之类的

**Comment by aloxc** [comment]
![Snipaste_2024-10-31_13-48-44](https://github.com/user-attachments/assets/27ccb9dd-0245-4cf4-83d7-6b7ab189de3d)

**Comment by Harlan-H** [comment]
这个提示很明显 是迅雷造成的呀 肯定是迅雷监控剪贴板造成的  
你这个得找迅雷解决啊 你找我没用 我又没法修复迅雷
