### ISSUE TITLE
EnqueueDownload的函数有个BUG。

### ISSUE THREAD

**Issue by LickJon** [Harlan-H/M3u8Downloader_H#38]
大佬，有几个BUG希望能修复一下：
1.这个函数能否做一个额外判断？这个只判断文件名，假设一个课程有10个章节，每个章节的第一个视频名称都叫“01.简介”。那么除了第一个章节的第一个“01.简介”外，其他9个章节的第一课都被认为是相同文件直接被忽略了，也就是说下载列表中只允许存在一个"01.简介"的视频，其他章节甚至其他课程如果包含同名文件只要没有被清除列表都会自动会忽略下载。盼修复。
2.另外如果以m3u8内容方式提交，下载完成后点击搜索的图标，能否以保存地址为定位标识？
3.当软件以管理权限允许后，地址栏不再支持拖曳添加任务，能否取消这个限制？小个别视频下载出错不管如何尝试都不能成功，需要删除列表重新添加才能正确下载。如果API添加方式不支持拖曳就得重开一个软件来完成。
4.API提交任务默认下，扩展名选择mp4的时候有一定概率无法正确合成，都是在合成步骤出错，看错误信息是路径变成乱码了。选择默认格式则正常。

 private void EnqueueDownload(DownloadViewModel download)
        {  
            var existingDownloads = Downloads.Where(d => d.VideoName == download.VideoName).FirstOrDefault();
            if (existingDownloads is not null)
                return;
            download.OnStart();
            Downloads.Insert(0, download);

        }

**Comment by Harlan-H** [comment]
1.你说的那个所谓的bug 他并不是bug 你既然知道 每一章节都有相同的标题 那你可以在名字上加上章节的名字啊 如果我改成你说的这种 那才是bug 软件因为没有数据库 所以无法保存下载队列的状态 所以设计之初就是为了 断点续传 只要输入相同的文件名 他就可以接着继续下载 
2.这个定位本来就是定位文件夹的 但是有的时候 好像确实会定位不到 等后期改版 我详细研究一下
3.这个问题没办法 这个是语言本身导致的 所以最好你是以管理员账号登录系统 这样哪怕不使用管理员权限打开 他一样是管理员权限的  就不会出现这个问题
4.一定概率无法合成 这种概率的问题 我无法解决 除非你能够在遇到的时候 发给我地址或者文件 我能复现这个问题才行 不然这个问题就没办法

**Comment by Harlan-H** [comment]
其实最早版本 是判断地址的 但是因为地址没法改 就导致真的没有办法重复下载 所以才改成了判断名字 因为名字不重要 你甚至可以不用写名字 软件也会自动生成名字 而且生成的那个名字 同名概率非常非常低 而且通过api模式可以动态修改掉保存路径
我好像知道了 api下载好像有bug  回头我修复一下吧 本来预想是通过api修改保存路径来实现改变名字哪怕相同 也可以让他下载的情况 看来那里还是有bug 回头我修复一下

**Comment by LickJon** [comment]
大佬，是这样的。多个章节存在同名文件还有个字幕等其他相关文件需要下载，如果强制改名会导致其他关联文件也需要一一对应的去修改文件名，能否以最终保存路径+文件名作为判断依据呢？例如最终保存路径是c:\第一章节\01.简介.mp4 。除非重复下载到同一个目录，不然雷同率几乎是0。这样不管多少章节都能自动处理。如果只是下载个别文件，手工更名是不麻烦，当处理大量文件的时候，就比较麻烦。

**Comment by Harlan-H** [comment]
你这个想法挺好的   因为开始给你回复第一条的时候 我给那个api模式忘了  正常来说同一个文件夹是不可能有两个一样同名的 所以我才那样说 给你回第二条的时候  我就想起来 那个api模式会出现你说的这个问题  这几天 我给他改好  


还有就是软件未来应该会支持下载mp3 mp4  字幕 弹幕等 集合下载方案  得等到4.0版本 可能得年前了 尽情期待哦

**Comment by LickJon** [comment]
哇哦，真是令人期待的4.0.感谢大佬。
