### ISSUE TITLE
大佬，Api是否有改动过，使用以下代码提交任务保存有些问题。

### ISSUE THREAD

**Issue by LickJon** [Harlan-H/M3u8Downloader_H#39]
大佬，Api是否有改动过，使用以下代码提交任务保存有些问题。
会直接无视保存路径与文件名，统一被保存在软件目录，并且保存文件名会以01.mp4-10.mp4循环反复覆盖。但是软件界面的任务中名字是正确的。

def post_m3u8_downapp(fileData, Savepath, Name):
    headers = {
        'User-Agent': 'Mozilla/5.0',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9'
    }
    try:
        response = r.post("http://127.0.0.1:65432/downloadbycontent", json={"content": fileData, "headers": headers, "savepath": Savepath, "name": Name})
        response.raise_for_status()
        print(f'M3U8 下载请求已发送: {Name}')
    except r.RequestException as e:
        print(f'M3U8 下载请求失败: {e}')

**Comment by Harlan-H** [comment]
公告写了 改的就是这个方法  只不过具体没有改动啥 就是原先进下载列表才解析 变成了直接解析 然后进下载列表 
你可以链接发给我 我正好这回有时间  我来测试一下

**Comment by Harlan-H** [comment]
不用发了 你说那个问题 我测试出来了  过一会发新版

**Comment by Harlan-H** [comment]
是不是你的savepath中或者vide
