### ISSUE TITLE
请问一下B站怎么下载呢?

### ISSUE THREAD

**Issue by mtvktvcn** [Harlan-H/M3u8Downloader_H#7]
请问一下B站怎么下载呢?
用了猫抓在B站也没看到有那个M38U的链接.

**Comment by Harlan-H** [comment]
b站直播是 m3u8得  直接复制b站直播得 视频地址  就可以下载了 不用获取m3u8
例如 https://live.bilibili.com/26389447
直接把这个地址复制到请求地址处  就会自动下载了

**Comment by Harlan-H** [comment]
> 请问一下B站怎么下载呢? 用了猫抓在B站也没看到有那个M38U的链接.

给你回了 你看下

**Comment by mtvktvcn** [comment]
明白了,是B站的直播,是我理解错了.感谢你的回复.软件确实很好用.
我再建议一点就是,关闭了软件之后,再开就没有记录了.
这点应该是可以优化一下的.

**Comment by Harlan-H** [comment]
> 明白了,是B站的直播,是我理解错了.感谢你的回复.软件确实很好用. 我再建议一点就是,关闭了软件之后,再开就没有记录了. 这点应该是可以优化一下的.

只不过你要真得想下载b站得视频 也容易 我另一个项目  就是b站下载器 只针对b站  你可以在我得52pojie个人空间或者github空间 看到那个项目

**Comment by Harlan-H** [comment]
客气
