### ISSUE TITLE
格式 是TS可以 选择MP4提示出错.

### ISSUE THREAD

**Issue by mtvktvcn** [Harlan-H/M3u8Downloader_H#8]
System.InvalidOperationException: ffmpeg异常退出 退出码 (1).
这个怎么解决呢?

**Comment by Harlan-H** [comment]
发个地址我看看 啥情况

**Comment by mtvktvcn** [comment]
> 发个地址我看看 啥情况

我重启电脑,试的时候正常了. 不好意思啊,

**Comment by Harlan-H** [comment]
> > 发个地址我看看 啥情况
> 
> 我重启电脑,试的时候正常了. 不好意思啊,

这没啥事  能反馈 就是好事  
我到是挺希望有人反馈 这类问题 最少能对修复软件有很大帮助得
下次遇到啥问题了 继续反馈
