### ISSUE TITLE
无法获取抖音VR直播的数据

### ISSUE THREAD

**Issue by zcgdash** [Harlan-H/M3u8Downloader_H#9]
抖音现在有VR直播，一般在晚上18点-22点之间，有一些主播在播。尝试录制视频时发现这些直播的地址是无法在电脑的浏览器里播放的，直接提示只能在手机上播放，而且该直播的源数据应该是8k左右格式的，但是最高清晰度貌似限制了只能在移动端播放，最高清晰度可能还限制了只能是pico设备。直接用本软件输入直播地址来获取的话，会提示获取失败。大佬能否使本程序支持直接下载vr直播的视频？
目前我采用real-url那个软件可以获取到m3u8地址，然后把链接中的hd5vr2d字样，改为uhdvr2d字样，就可以用本软件下载4k的单画面视频，但仍然不能下载8k左右格式的原画面。

**Comment by zcgdash** [comment]
比如这个主播的链接https://v.douyin.com/h6ETysM/，直接输入无法获取，在浏览器里输这个地址提示只能在手机上播放。用real-url可以得到http://pull-hs-f5.flive.douyincdn.com/vrthird/stream-112110736827220672_hd5vr2d/index.m3u8。我把这个地址改为http://pull-hs-f5.flive.douyincdn.com/vrthird/stream-112110736827220672_uhd5vr2d/index.m3u8，就可以下载4k分辨率的了。但是8k无法下载。real-url也只能获取到4k地址，获取不到8k.

**Comment by Harlan-H** [comment]
回头我看一下
